image: docker

stages:
  - build

variables:
  IMAGE_TAG: "${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}"

build:
  stage: build
  script:
    - docker login --username="$CI_REGISTRY_USER" --password="$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    - docker build -t "${IMAGE_TAG}" .
    - docker tag "${IMAGE_TAG}" "${CI_REGISTRY_IMAGE}:staging"
    - docker push "${IMAGE_TAG}"
    - docker push "${CI_REGISTRY_IMAGE}:staging"
